num1=int(input("enter number 1:"))
num2=int(input("enter number 2:"))
print("before swap number1=",num1)
print("before swap number2=",num2)
temp=num1
num1=num2
num2=temp
print("after swap number1=",num1)
print(" after swap number2=",num2)